### PR TITLE
OPENTOK-40778: Official OpenTok samples for Linux SDK

### PR DESCRIPTION
**Pull request by jaoo**
#### What is this PR doing?

Reviewing current official OpenTok samples for Linux SDK.

#### How should this be manually tested?

Install dependencies, build and run!

### CODE REVIEW

**Comment by joliveraortega** [comment]
@jeffswartz This is the PR you should edit. Your changes at https://github.com/opentok/opentok-linux-sdk-samples/pull/10 have to be here.

**Comment by chetanvangadiTokbox** [comment]
This is tested and ticket closed.

**Comment by chetanvangadiTokbox** [comment]
LGTM

**Comment by joliveraortega** [comment]
> This is tested and ticket closed.
> I have seen I had to install more dependency other then listed in Readme, Can this also be included.
> `-- Checking for one of the modules 'libcurl'
> CMake Error at /usr/local/share/cmake-3.17/Modules/FindPkgConfig.cmake:745 (message):
> None of the required 'libcurl' found
> Call Stack (most recent call first):
> CMakeLists.txt:13 (PKG_SEARCH_MODULE)
> 
> -- Checking for one of the modules 'jansson'
> CMake Error at /usr/local/share/cmake-3.17/Modules/FindPkgConfig.cmake:745 (message):
> None of the required 'jansson' found
> Call Stack (most recent call first):
> CMakeLists.txt:14 (PKG_SEARCH_MODULE)
> 
> -- Checking for one of the modules 'libunwind'
> CMake Error at /usr/local/share/cmake-3.17/Modules/FindPkgConfig.cmake:745 (message):
> None of the required 'libunwind' found
> Call Stack (most recent call first):
> CMakeLists.txt:15 (PKG_SEARCH_MODULE)
> 
> -- Checking for one of the modules 'libuv'
> CMake Error at /usr/local/share/cmake-3.17/Modules/FindPkgConfig.cmake:745 (message):
> None of the required 'libuv' found
> Call Stack (most recent call first):
> CMakeLists.txt:16 (PKG_SEARCH_MODULE)`

Seems to me you where testing the most recent commit in the. branch. None of the dependencies listed in the output you. pasted are required. They were long time ago.

**Review by rperezcubero — APPROVED** [review]

**Pull request merged**
