### PR TITLE
Update Linux SDK version (README only)

### PR DESCRIPTION
**Pull request by goncalocostamendes**
#### What is this PR doing?

Update OPENTOK SDK Version

#### How should this be manually tested?

Clone samples from https://github.com/opentok/opentok-linux-sdk-samples
Run command

> `wget` https://tokbox.com/downloads/libopentok_linux_llvm_x86_64-2.23.0

Uncrompress 

> tar xvf libopentok_linux_llvm_x86_64-2.23.0
> export LIBOPENTOK_PATH=<path_to_SDK>

Build sample and run it

### CODE REVIEW

**Review by sergioturgil-vonage — APPROVED** [review]
Looks in order

**Review by juliobecerragomez — APPROVED** [review]
LGTM! Not related to your change. But I always wonder what's the criteria to decide a new version (2.23 in this case) is supposed to work on a "non Debian based" linux.

**Comment by goncalocostamendes** [comment]
@juliobecerragomez that title is indeed not amazing. What I believe it was meant, is to explain that instead of download it from packagecloud, you can get it using wget command as well

**Comment by juliobecerragomez** [comment]
> @juliobecerragomez that title is indeed not amazing. What I believe it was meant, is to explain that instead of download it from packagecloud, you can get it using wget command as well

Sure. My concern is about compatibility with older versions. But

**Pull request merged**
